GET http://localhost:5000/kategori

###
GET http://localhost:5000/kategori/1

###
GET http://localhost:5000/products

###
GET http://localhost:5000/transaksi

# tambah
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "radit",
    "email": "raditus05@gmail.com",
    "password": "12345678",
    "role": "admin"
}

###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/b66d5966-4ebc-44ed-a1d0-0bdb809252d7